# Generated by Django 4.2.4 on 2023-08-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_intro_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='rezume_text',
            field=models.CharField(default='Default Resume Text', max_length=50),
        ),
    ]
