# Generated by Django 4.2.4 on 2023-08-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0004_intro_logo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='icon',
            field=models.CharField(default='fab fa-linkedin', max_length=50),
        ),
        migrations.AddField(
            model_name='intro',
            name='linkedin_url',
            field=models.URLField(default='https://www.linkedin.com/in/jigar-sable/'),
        ),
    ]
