# Generated by Django 4.2.4 on 2023-08-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0007_intro_icon_intro_icon_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='icon_url',
            new_name='linkedin_url',
        ),
    ]
