# Generated by Django 4.2.4 on 2023-08-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0008_rename_icon_url_intro_linkedin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='linkedin_url',
        ),
    ]
