# Generated by Django 4.2.4 on 2023-08-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0010_icons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icons',
        ),
    ]
