# Generated by Django 4.2.4 on 2023-08-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0013_intro_logo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='navbar_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home', models.CharField(default='Home', max_length=50)),
                ('About', models.CharField(default='About', max_length=50)),
                ('Skills', models.CharField(default='Skills', max_length=50)),
                ('Education', models.CharField(default='Education', max_length=50)),
                ('Work', models.CharField(default='Work', max_length=50)),
                ('Experience', models.CharField(default='Experience', max_length=50)),
                ('Contact', models.CharField(default='Contact', max_length=50)),
            ],
        ),
    ]
