# Generated by Django 4.2.4 on 2023-08-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0014_navbar_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(default='Home', max_length=50)),
                ('about', models.CharField(default='About', max_length=50)),
                ('skills', models.CharField(default='Skills', max_length=50)),
                ('education', models.CharField(default='Education', max_length=50)),
                ('work', models.CharField(default='Work', max_length=50)),
                ('experience', models.CharField(default='Experience', max_length=50)),
                ('contact', models.CharField(default='Contact', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='navbar_link',
        ),
    ]
