# Generated by Django 4.2.4 on 2023-08-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0015_navbarlink_delete_navbar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarlink',
            name='Navbarga_nom_joylash',
            field=models.TextField(default='Navbarga_nom_joylash'),
        ),
    ]
