# Generated by Django 4.2.4 on 2023-08-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0016_navbarlink_navbarga_nom_joylash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarlink',
            name='Navbarga_nom_joylash',
        ),
    ]
