# Generated by Django 4.2.4 on 2023-08-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0017_remove_navbarlink_navbarga_nom_joylash'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_haqimda', models.CharField(default='Men haqimda', max_length=50)),
                ('mening_ismim', models.CharField(default="Shohbozbek Turg'unov", max_length=50)),
                ('kasbim', models.CharField(default='Full Stack Developer', max_length=50)),
                ('men_haqimda_description', models.TextField()),
            ],
        ),
    ]
