# Generated by Django 4.2.4 on 2023-08-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0020_alter_about_mening_rasmim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(default='Texnologiyar', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='mening_rasmim',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
