# Generated by Django 4.2.4 on 2023-08-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0021_skills_alter_about_mening_rasmim'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='texnologiyalar_nomi',
            field=models.CharField(default='Texnologiya', max_length=50),
        ),
        migrations.AddField(
            model_name='skills',
            name='texnologiyalar_rasmi',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
