# Generated by Django 4.2.4 on 2023-08-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0022_skills_texnologiyalar_nomi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skills_name',
        ),
    ]
