# Generated by Django 4.2.4 on 2023-08-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0023_remove_skills_skills_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texnologiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
