# Generated by Django 4.2.4 on 2023-08-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0025_alter_texnologiya_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texnologiya',
            old_name='image',
            new_name='texnologiya_image',
        ),
        migrations.RenameField(
            model_name='texnologiya',
            old_name='name',
            new_name='texnologiya_name',
        ),
    ]
