# Generated by Django 4.2.4 on 2023-08-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0026_rename_image_texnologiya_texnologiya_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texnologiya',
        ),
    ]
