# Generated by Django 4.2.4 on 2023-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0028_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(upload_to='images/skills/'),
        ),
    ]
