# Generated by Django 4.2.4 on 2023-09-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0029_alter_skill_skill_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='konikmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konikma_shunchaki', models.TextField()),
            ],
        ),
    ]
