# Generated by Django 4.2.4 on 2023-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0030_konikmalar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konikmalar',
            name='konikma_shunchaki',
            field=models.CharField(max_length=50),
        ),
    ]
